sipcapture/captagent

captagent.spec.in, src/conf_function.h
+ Removed fixup_function def from conf_function.h
+ Added X attribute to main executable for captagent application
=> Captagent6: some fixes whil bilding on CentOS6 x86_64

captagent/mod/proto_rtcp/proto_rtcp.c, captagent/mod/proto_uni/proto_uni.c
While testing a capture with device "any" for proto_uni, I noticed that packets were received but not recognized as IPv4 nor IPv6, and the packets discarded. Specifying the device (e.g. 'lo') was instead working correctly.
Experimenting with changes to the offset I noticed - coincidentally - that there was a wrong offset of 2: adding a fixed 2 to link_offset made the capture work for device "any" too. I then noticed that proto_uni was correctly setting link_offset to 16 (DLT_LINUX_SLL), but then at the moment of entering into the callback function link_offset was back to 14. The interpretation is that link_offset from proto_rtcp was causing the reset.
This pull request sets link_offset as static, then changes the variable name for proto_rtcp.
I have tested proto_uni with this patch and …
=> Ensure link offset of proto_rtcp mod does not clash with proto_uni mod

src/modules/protocol/sip/protocol_sip.c
In function w_sip_check when param1 has value "method", it always print error message.
=> Fix sip param checking

pkg/debian/captagent.init, pkg/debian/control, pkg/debian/source/options
There were some missing build and runtime dependencies in the debian control file. Also, when building with Jenkins, Upload failed when building for Jessie, because it expected a .xz tarball, but got a .gz tarball. The options file disables this behavior.
=> Fix Debian package building

.gitignore, conf/captagent.xml.in, configure.ac, include/captagent/modules.h, m4/as-ac-expand.m4, pkg/debian/captagent.init.in, pkg/debian/rules
This patch set updates the Debian packaging and other aspects of the build system to make sure that a Debian package can be built and is usable immediately after installation without any manual config.
packaging is possible with the following commands
```
ln -s pkg/debian
debuild -uc -us
```
=> Fix Debian packaging

pkg/debian/captagent.default, pkg/debian/captagent.init.in, pkg/debian/control
We are creating debian packages for captagent, but we don't run them via init script. So I added a pretty basic defaults file, which makes captagent by default not start because the RUN_CAPTAGENT variable is set to "no". Before the first start, you probably want to edit the configuration anyways. 
Also, there is a new dependency to libuv1, so I added that. But since this lib is not available in Wheezy, you need at least Jessie for the package to build.
=> debian pkg: require libuv1(-dev) and make init script use default file

pkg/debian/control
I updated the package dependency from libuv1, which doesn't exist on Debian, to libuv0.10, which exists on both Debian and Ubuntu.
=> libuv1 packages do not exist on debian

include/captagent/structure.h, src/modules/socket/pcap/Makefile.am, src/modules/socket/pcap/sctp_support.c, src/modules/socket/pcap/sctp_support.h, src/modules/socket/pcap/socket_pcap.c
Add initial support for SCTP and parsing SCTP data chunks. It has
been "verified" with a single SCTP packet containing exactly one
chunk. The code does not support fragmentation of data chunks, the
input validation might not be enough. I didn't understand the
frag_offset calculation (as once we have the SCTP header all IP
offsets are already applied?).
In contrast to TCP and UDP a single frame can contain multiple
chunks and these are dispatched one after another. The counters
are for sctp frames. In general "full_packet" as an option does
not make sense and the hdrlen has not been set. It might require
more architecture changes to move forward. The code also does not
attempt to identify retransmits of a data chunk.
Extend the msg structure to transport the ppid which will allow
to parse …
=> pcap: Add initial version of sctp support

conf/captagent.xml.in, conf/protocol_ss7.xml, m4/modules_makefiles.m4, src/Makefile.am, src/modules/protocol/ss7/Makefile.am, src/modules/protocol/ss7/protocol_ss7.c
It seemed difficult to have let's say the M2UA protocol pass it to MTP and then pass it to ISUP. Instead there is a single SS7 protocol that can do the right thing based on the PPID of the sctp data chunk. Add initial implementation for M2UA, MTPl3 and a bit of ISUP.
=> Introduce a "ss7" protocol

src/modules/transport/hep/transport_hep.c, src/modules/transport/hep/transport_hep.h
Implementation of TCP re-connect logic.  Instead of just re-connecting as soon as we are disconnected which can cause excessive re-connects when server is down, it will ensure we only try to re-connect every 2 seconds.  Also note that SIGPIPE is ignored which is a best practice with TCP-based applications.
=> Add support for TCP re-connect.

src/modules/transport/hep/transport_hep.c
Found a socket leak when letting agent run for extended period of time while server is down.  Confirmed number of sockets opened by agent remains steady now when TCP connect immediately fails repeatedly as well as when TCP connection opens and closes repeatedly.
=> Fix socket leak with TCP re-connect.

src/modules/socket/pcap/socket_pcap.c
Appears that the 802.1Q header was being allowed for manually in malloc, memcpy, reasm_ip_next and in calculating len, when it had already been allowed for in hdr_offset variable.
This appears to have been responsible for https://github.com/sipcapture/captagent/issues/96 which is fixed on my system by this patch
**Note: I have not tested in a VLAN untagged environment or with IPv6**
=> Fix: 802.1Q VLAN header accounted for twice in packet length

src/modules/protocol/tcp/Makefile.am
Any build from "make dist" produced tarball fails without this fix.
=> Added: hash_structure.h

pkg/debian/rules, src/modules/socket/pcap/socket_pcap.c
Previously, en enabled setting of capture_filter option was needed to turn on the reassembly of fragmented packets. Actually it should depend on a filter being set. So the section got rewritten.
Additionally, Debian packages are now built with IPv6 support.
Fixes #78.
=> Fix enabling of Packet reassembly

src/modules/socket/pcap/Makefile.am
Any build from "make dist" produced tarball fails without this fix.
=> Added: uthash.h

src/modules/interface/http/civetweb.c, src/modules/interface/http/interface_http.c
On systems without glibc, as Alpine Linux, you might lack definition of
PATH_MAX.  This patch simply assure that the definition exists, set to
4096 which is the standard, otherwise the code will break,as it is
breaking today:
http://build.alpinelinux.org/buildlogs/build-edge-ppc64le/testing/captagent/captagent-6.1.0.20-r3.log
It is important to say that MAX_PATH is also not a definition we have on
MUSL systems.
=> Define PATH_MAX if not defined

m4/modules_makefiles.m4, src/modules/protocol/rtcp/protocol_rtcp.c, src/modules/protocol/rtcpxr/Makefile.am, src/modules/protocol/rtcpxr/captureplan/Makefile.am, src/modules/protocol/rtcpxr/parser_rtcpxr.c, src/modules/protocol/rtcpxr/parser_rtcpxr.h, src/modules/protocol/rtcpxr/protocol_rtcpxr.c, src/modules/protocol/rtcpxr/protocol_rtcpxr.h
m4/modules_makefiles.m4:
* add modules/protocol/rtcpxr makefiles
* renamed module socket/{rtcpxr,collector}
modules/protocol/rtcp/protocol_rtcp.c:
* remove duplicate function
modules/protocol/rtcpxr/Makefile.am:
* fix duplicate varnames
src/modules/protocol/rtcpxr/captureplan/Makefile.am:
* fix typo in path to captureplan
src/modules/protocol/rtcpxr/parser_rtcpxr.c:
* fix typo to header file
* fix warning about different pointer signedness
src/modules/protocol/rtcpxr/parser_rtcpxr.h:
* fix missing macro
src/modules/protocol/rtcpxr/protocol_rtcpxr.c:
* fix typo in logger macro
* remove undefined variable
* fix free'ing int
src/modules/protocol/rtcpxr/protocol_rtcpxr.h
* add missing stats struct (only free'd, besides unused)
* add missing struct for protocol profiles (besides different …
=> fix build errors

src/modules/database/hash/captarray.c, src/modules/database/hash/database_hash.c, src/modules/protocol/rtcp/protocol_rtcp.c, src/modules/socket/pcap/socket_pcap.c, src/modules/socket/pcap/socket_pcap.h, src/modules/socket/pcap/tcpreasm.c
This PR primarily fixes bugs in socket_pcap. Details are in the individual commits.
The last patch fixes a bug with inverse logic causing the timer not to run.
Furthermore, this patchset reduces verbosity by moving printf's to LDEBUG.
These fixes have no corresponding issue filed.
=> Random fixes, primarily to get socket_pcap working

.travis.yml, test/README.md, test/hep.js, test/index.js, test/init.js, test/package-lock.json, test/package.json
This skeleton provides a setup for testing Captagent builds for basic and advanced issues using `nodejs` and `mocha` including HEP dissection with `hep-js` for deep validation of HEP IN/OUT pipelines. 
Lots of work still to be done but this is a start. Instructions in `README` inside the `/test` folder.
=> Basic CI testing of Captagent

src/modules/socket/pcap/socket_pcap.c
Without this patch, sending SIGTERM causes captagent to hang on shutdown of the pcap socket module.  Tested on debian buster.
calling pcap_breakloop from a seperate pthread requires the pthreads running pcap_loop to be pthread_cancel'd.  From the pcap_breakloop manpage:
> Note  also  that, in a multi-threaded application, if one thread is blocked in pcap_dispatch(), pcap_loop(), pcap_next(), or pcap_next_ex(), a call to pcap_breakloop() in a different thread will not
>        unblock that thread; you will need to use whatever mechanism the OS provides for breaking a thread out of blocking calls in order to unblock the thread, such as thread cancellation in  systems  that
>        support POSIX threads.
This one-liner fixes the behaviour on my Debian 10 systems
=> Fix pthread hang in pcap module teardown

src/modules/socket/pcap/socket_pcap.c
New captagent setup using PCAP and receiving port mirrored traffic from several ports in the environment.  Some ports with VLAN tags, and others without.  Captagent was crashing with a SegFault whenever a packet with the 802.1Q (Ethertype 0x8100) header arrived.  GDB output below of the crash.
The changes in this PR got things running nicely for me.   Heplify had already worked perfectly with this mirrored traffic, but I have a desire to use for output_json for something else so I want to use captagent instead.   Thanks for the great projects!
```
gdb
Core was generated by `/usr/local/captagent/sbin/captagent -f /etc/captagent/captagent.xml'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  callback_proto (arg=<optimized out>, pkthdr=0x7f413282ee00, packet=0x7f4132830082 …
```
=> Seg Fault while using socket_pcap and receiving 802.1q VLAN tagged traffic

.gitignore, include/captagent/api.h, include/captagent/modules.h, src/captagent.c, src/conf_function.c, src/conf_function.h, src/modules.c, src/modules/protocol/tls/decryption.h
This does not fix any of the other bugs I spotted along the way
(module_path being assigned a static string and then later free()d for
example).
=> Minimum set of changes to make gcc10 compatible.

src/captagent.c
declaration.
Signed-off-by: Jaco Kroon <jaco@uls.co.za>
=> Move declaration of usage() function to avoid conflicting implicit

src/modules/socket/pcap/socket_pcap.h
=> socket/pcap: Define SLL2 for old libpcap versions

src/modules/socket/pcap/socket_pcap.h
fixes #262 
https://github.com/the-tcpdump-group/libpcap/commit/8cff296dc7c321c76933359d586dbde5b580ce8c#diff-71e2d278108185f61bfa3965238988c3b2a9f479a7582e87488af35be15444e7
=> socket/pcap: Define SLL2 struct

src/modules/socket/pcap/socket_pcap.c
From the manpage [1]
```
pcap_stats() is supported only on live captures, not on
``savefiles''; no statistics are stored in ``savefiles'', so no
statistics are available when reading from a ``savefile''.
```
[1] https://man7.org/linux/man-pages/man3/pcap_stats.3pcap.html
=> Socket pcap stats offline

src/modules/socket/pcap/socket_pcap.c
Fix incompabtible cast errors/warnings (depending on compiler)
=> socket/pcap: Fix compiler warnings
